[package]
name = "cm-jclass"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bytes.workspace = true
byteorder.workspace = true

[lints.clippy]
nursery = { level = "warn", priority = -1 }
clone_on_ref_ptr = "warn"
#pedantic = { level = "warn", priority = -1 }
